FROM golang:1.24-alpine

WORKDIR /app/backend

RUN apk add --no-cache git

COPY backend/go.mod backend/go.sum* ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

CMD ["go", "run", "./cmd/api"]
