FROM node:22-alpine

WORKDIR /app

COPY frontend-public/package.json frontend-public/package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm \
    npm install

# In dev, we use volumes, but we need the files for the initial build if any
COPY frontend-public /app

CMD ["npm", "run", "dev"]
